# Generated by Django 5.2.12 on 2026-03-14 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0002_alter_station_id_alter_stationalias_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_at', models.DateTimeField()),
                ('variable_code', models.CharField(max_length=50)),
                ('raw_value', models.FloatField(blank=True, null=True)),
                ('cleaned_value', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('qc_flag', models.CharField(default='unchecked', max_length=20)),
                ('qc_notes', models.TextField(blank=True, null=True)),
                ('ingest_time', models.DateTimeField()),
                ('payload_ref', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'observations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StationHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_at', models.DateTimeField(db_index=True)),
                ('battery_voltage', models.FloatField(blank=True, null=True)),
                ('signal_strength', models.FloatField(blank=True, null=True)),
                ('internal_temp', models.FloatField(blank=True, null=True)),
                ('uptime_seconds', models.BigIntegerField(blank=True, null=True)),
                ('packet_loss_pct', models.FloatField(blank=True, null=True)),
                ('health_status', models.CharField(choices=[('ok', 'OK'), ('warning', 'Warning'), ('critical', 'Critical'), ('offline', 'Offline'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=20)),
                ('ingest_time', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='stations.station')),
            ],
            options={
                'db_table': 'station_health',
                'indexes': [models.Index(fields=['station', 'observed_at'], name='health_station_time_idx'), models.Index(fields=['health_status'], name='health_status_idx')],
            },
        ),
    ]
