# Generated by Django 5.2.12 on 2026-03-13 10:58

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_code', models.CharField(help_text='Internal unique station code used by the platform.', max_length=100, unique=True)),
                ('wmo_id', models.CharField(blank=True, db_index=True, help_text='Official WMO station identifier where available.', max_length=50, null=True)),
                ('name', models.CharField(max_length=255)),
                ('country_code', models.CharField(blank=True, db_index=True, help_text='ISO 3166-1 alpha-3 country code.', max_length=3, null=True)),
                ('admin1', models.CharField(blank=True, max_length=150, null=True)),
                ('admin2', models.CharField(blank=True, max_length=150, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(geography=True, help_text='Station location stored as longitude/latitude point in WGS84.', srid=4326)),
                ('elevation_m', models.DecimalField(blank=True, decimal_places=2, help_text='Elevation in meters above sea level.', max_digits=8, null=True)),
                ('agency', models.CharField(blank=True, help_text='Owning or operating agency.', max_length=255, null=True)),
                ('station_type', models.CharField(choices=[('synop', 'SYNOP'), ('aws', 'Automatic Weather Station'), ('agro', 'Agrometeorological Station'), ('rainfall', 'Rainfall Station'), ('climatological', 'Climatological Station'), ('hydro', 'Hydrological Station'), ('other', 'Other')], db_index=True, default='aws', max_length=30)),
                ('install_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'stations',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['station_code'], name='stations_code_idx'), models.Index(fields=['wmo_id'], name='stations_wmo_idx'), models.Index(fields=['country_code'], name='stations_country_idx'), models.Index(fields=['station_type'], name='stations_type_idx'), models.Index(fields=['is_active'], name='stations_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='StationAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(help_text='Source system name, e.g. WIS2, NOAA, OGIMET.', max_length=100)),
                ('alias_code', models.CharField(help_text='External source station code.', max_length=100)),
                ('alias_name', models.CharField(blank=True, help_text='Optional station name used by the external source.', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='stations.station')),
            ],
            options={
                'db_table': 'station_aliases',
                'indexes': [models.Index(fields=['source_name'], name='st_alias_source_idx'), models.Index(fields=['alias_code'], name='st_alias_code_idx')],
                'unique_together': {('source_name', 'alias_code')},
            },
        ),
        migrations.CreateModel(
            name='StationSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_code', models.CharField(help_text='Unique code for the sensor within the station.', max_length=100)),
                ('variable_code', models.CharField(choices=[('temp', 'Air Temperature'), ('rainfall', 'Rainfall'), ('rh', 'Relative Humidity'), ('pressure', 'Pressure'), ('wind_speed', 'Wind Speed'), ('wind_direction', 'Wind Direction'), ('solar_radiation', 'Solar Radiation'), ('soil_moisture', 'Soil Moisture'), ('soil_temp', 'Soil Temperature'), ('water_level', 'Water Level'), ('other', 'Other')], db_index=True, max_length=50)),
                ('unit', models.CharField(help_text='Measurement unit, e.g. degC, mm, %, hPa.', max_length=50)),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('install_date', models.DateField(blank=True, null=True)),
                ('height_m', models.DecimalField(blank=True, decimal_places=2, help_text='Sensor height above ground in meters where applicable.', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(-10), django.core.validators.MaxValueValidator(100)])),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('faulty', 'Faulty'), ('maintenance', 'Maintenance')], db_index=True, default='active', max_length=20)),
                ('metadata_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='stations.station')),
            ],
            options={
                'db_table': 'station_sensors',
                'indexes': [models.Index(fields=['station'], name='st_sensor_station_idx'), models.Index(fields=['variable_code'], name='st_sensor_var_idx'), models.Index(fields=['status'], name='st_sensor_status_idx')],
                'unique_together': {('station', 'sensor_code')},
            },
        ),
    ]
