# Generated by Django 5.2.13 on 2026-04-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0007_station_canonical_code'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='station',
            index=models.Index(fields=['canonical_code'], name='stations_canonical_idx'),
        ),
    ]
