# Generated by Django 5.2.10 on 2026-02-02 06:39

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', wagtail.fields.RichTextField(blank=True)),
                ('dataset_id', models.SlugField(help_text='Stable id used by infra and APIs, e.g. cdi, spi, sma', max_length=80, unique=True)),
                ('dataset_type', models.CharField(choices=[('raster', 'Raster'), ('vector', 'Vector')], max_length=10)),
                ('cadence', models.CharField(choices=[('daily', 'Daily'), ('dekadal', 'Dekadal'), ('monthly', 'Monthly'), ('seasonal', 'Seasonal')], max_length=10)),
                ('stac_collection_id', models.CharField(blank=True, help_text='If blank, defaults to dataset_id', max_length=120)),
                ('is_published_for_ui', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProjectPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
