# Generated by Django 5.2.10 on 2026-02-02 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('layer_id', models.SlugField(max_length=120, unique=True)),
                ('layer_type', models.CharField(choices=[('raster', 'Raster'), ('vector', 'Vector')], max_length=10)),
                ('tile_template', models.CharField(help_text='Example raster: https://tiles.domain/tiles/{z}/{x}/{y}.png  | vector: https://vectors.domain/collections/mytable/tiles/{z}/{x}/{y}.pbf', max_length=300)),
                ('tile_params', models.JSONField(blank=True, default=dict, help_text='JSON dict of default params, e.g. {"assets":"cdi","bidx":1,"rescale":"0,100"}')),
                ('default_visible', models.BooleanField(default=False)),
                ('opacity', models.FloatField(default=0.85)),
                ('minzoom', models.IntegerField(default=0)),
                ('maxzoom', models.IntegerField(default=12)),
                ('legend', models.JSONField(blank=True, default=dict, help_text='JSON legend, e.g. {"type":"continuous","label":"CDI","colors":["#d73027","#fee08b","#1a9850"],"breaks":[0,50,100]}')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layer_configs', to='catalog.datasetpage')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
