# Generated by Django 5.2.10 on 2026-02-02 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_layer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='layer',
            options={},
        ),
        migrations.AlterField(
            model_name='layer',
            name='legend',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='layer',
            name='tile_params',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='layer',
            name='tile_template',
            field=models.CharField(max_length=300),
        ),
    ]
