# Generated by Django 5.2.14 on 2026-05-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_layer_style_cluster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='legend',
            field=models.JSONField(blank=True, default=dict, help_text='Label → color map for the UI legend, e.g. {"Low": "#d73027", "High": "#1a9850"}.'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='style_scheme',
            field=models.CharField(choices=[('discrete', 'Discrete'), ('linear', 'Linear'), ('band', 'Band')], default='discrete', help_text='Discrete/linear: color stops become a TiTiler colormap. Band: RGB compositing (default bidx=1,2,3) via band_visualization_params in tile_params.', max_length=20),
        ),
    ]
