# Generated by Django 5.2.14 on 2026-05-19 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_layericon_and_layer_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='layer',
            options={'ordering': ['sort_order', 'title'], 'verbose_name': 'Layer', 'verbose_name_plural': 'Layers'},
        ),
    ]
