# Generated by Django 5.2.14 on 2026-06-03 09:57

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_geoserverlayer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geoserverlayer',
            options={'ordering': ['sort_order', 'title'], 'verbose_name': 'ADMA GeoServer layer', 'verbose_name_plural': 'ADMA GeoServer layers'},
        ),
        migrations.AlterField(
            model_name='datasetpage',
            name='icon',
            field=models.ForeignKey(blank=True, help_text='Toolbar icon for this dataset in the UI.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='datasets', to='catalog.layericon'),
        ),
        migrations.AlterField(
            model_name='geoserverlayer',
            name='availability_api_url',
            field=models.URLField(help_text='Base URL of the availability endpoint, e.g. https://ada.acmad.org/api/data_api/rs_data/get_available_datasets/'),
        ),
        migrations.AlterField(
            model_name='geoserverlayer',
            name='description',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='geoserverlayer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='geoserverlayer',
            name='legend',
            field=models.JSONField(blank=True, default=dict, help_text='Label → hex color map, e.g. {"No Warning": "#ffffff"}'),
        ),
        migrations.AlterField(
            model_name='geoserverlayer',
            name='methodology',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='geoserverlayer',
            name='resolution',
            field=models.CharField(blank=True, help_text='e.g. 5 km', max_length=100),
        ),
        migrations.AlterField(
            model_name='geoserverlayer',
            name='timescale',
            field=models.CharField(blank=True, help_text='Replaces {TS} in the URL template, e.g. 48 for SPI-48', max_length=20),
        ),
        migrations.AlterField(
            model_name='geoserverlayer',
            name='update_frequency',
            field=models.CharField(blank=True, help_text='e.g. Every 10 days', max_length=100),
        ),
        migrations.AlterField(
            model_name='geoserverlayer',
            name='wms_url_template',
            field=models.TextField(help_text='Full WMS URL template. Use {year}, {MM}, {DD}, {TS} as date placeholders. Keep {bbox-epsg-3857} — MapLibre fills it in dynamically. Copy the url_template value from the external availability API response.'),
        ),
        migrations.AlterField(
            model_name='hazardcategory',
            name='external_system_name',
            field=models.CharField(blank=True, help_text='Name of the linked external system, e.g. Africa Drought System', max_length=200),
        ),
        migrations.AlterField(
            model_name='hazardcategory',
            name='external_system_url',
            field=models.URLField(blank=True, help_text="URL for the 'Go to [System]' button in the layer details panel."),
        ),
        migrations.AlterField(
            model_name='hazardcategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='methodology',
            field=wagtail.fields.RichTextField(blank=True, help_text='Methodology description shown in the full details panel.'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='methodology_url',
            field=models.URLField(blank=True, help_text='Link to external methodology documentation.'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='resolution',
            field=models.CharField(blank=True, help_text='Spatial resolution, e.g. 5 km', max_length=100),
        ),
        migrations.AlterField(
            model_name='layer',
            name='source_organization',
            field=models.CharField(blank=True, help_text='Data source / producer, e.g. ACMAD / Africa Drought System', max_length=200),
        ),
        migrations.AlterField(
            model_name='layer',
            name='update_frequency',
            field=models.CharField(blank=True, help_text='How often data is updated, e.g. Every 10 days', max_length=100),
        ),
        migrations.AlterField(
            model_name='projectinclusion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projectinclusion',
            name='project',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='inclusions', to='catalog.projectpage'),
        ),
    ]
