# Generated by Django 5.2.14 on 2026-06-03 20:46

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_rename_geoserverlayer_verbose'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticWmsLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_id', models.SlugField(help_text='Unique ID used by the catalog API, e.g. countries-boundary', unique=True)),
                ('title', models.CharField(max_length=200)),
                ('is_published_for_ui', models.BooleanField(default=False)),
                ('tile_url', models.TextField(help_text='Full tile URL. Use {bbox-epsg-3857} for WMS GetMap requests, or {z}/{x}/{y} placeholders for XYZ/TMS tile services.')),
                ('legend', models.JSONField(blank=True, default=dict, help_text='Label → hex color map, e.g. {"Country border": "#333333"}')),
                ('description', wagtail.fields.RichTextField(blank=True)),
                ('default_visible', models.BooleanField(default=False)),
                ('opacity', models.FloatField(default=0.85)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('color_class', models.CharField(blank=True, default='text-blue-600', max_length=80)),
                ('coverage', models.CharField(blank=True, default='Africa', max_length=200)),
                ('source_organization', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hazard_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.hazardcategory')),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.layericon')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='static_wms_layers', to='catalog.projectpage')),
            ],
            options={
                'verbose_name': 'Static WMS / tile layer',
                'verbose_name_plural': 'Static WMS / tile layers',
                'ordering': ['sort_order', 'title'],
            },
        ),
    ]
