# Generated by Django 5.2.15 on 2026-06-19 06:56

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_staticwmslayer'),
        ('stations', '0010_station_has_observations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetpage',
            name='cadence',
            field=models.CharField(choices=[('daily', 'Daily'), ('dekadal', 'Dekadal'), ('monthly', 'Monthly'), ('seasonal', 'Seasonal'), ('annual', 'Annual')], max_length=10),
        ),
        migrations.AlterField(
            model_name='geoserverlayer',
            name='cadence',
            field=models.CharField(choices=[('daily', 'Daily'), ('dekadal', 'Dekadal'), ('monthly', 'Monthly'), ('seasonal', 'Seasonal'), ('annual', 'Annual')], max_length=10),
        ),
        migrations.CreateModel(
            name='ProjectCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='stations.countryboundary')),
                ('project', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='supported_countries', to='catalog.projectpage')),
            ],
            options={
                'verbose_name': 'Supported country',
                'verbose_name_plural': 'Supported countries',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
