# Generated by Django 5.2.15 on 2026-06-22 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_add_legend_description'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='hero_image',
            field=models.ForeignKey(blank=True, help_text='Background image shown on the project homepage.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='legend_description',
            field=models.TextField(blank=True, help_text="Short text shown as 'Legend' in the info panel (separate from the main description)."),
        ),
    ]
