# Generated by Django 5.2.15 on 2026-06-22 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_projectpage_hero_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='cities_count',
            field=models.CharField(blank=True, help_text="Cities stat on the homepage, e.g. '15+'.", max_length=20),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='headline',
            field=models.CharField(blank=True, help_text='Hero heading shown on the project homepage.', max_length=300),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='subtitle',
            field=models.TextField(blank=True, help_text='Short paragraph below the headline on the homepage.'),
        ),
    ]
