# Generated by Django 5.2.15 on 2026-06-22 06:36

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_projectpage_cities_count_projectpage_headline_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='about_description',
            field=models.TextField(blank=True, help_text='Body paragraph describing the project on the About page.'),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='about_image',
            field=models.ForeignKey(blank=True, help_text='Image shown on the right side of the About hero section.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='about_intro',
            field=models.CharField(blank=True, help_text="Green tagline below the title, e.g. 'Climate evidence for cooler, greener cities'.", max_length=500),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='about_title',
            field=models.CharField(blank=True, help_text="Heading for the About section, e.g. 'About e-SAFARI'.", max_length=300),
        ),
        migrations.CreateModel(
            name='ProjectFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('icon_name', models.CharField(blank=True, help_text="Lucide icon slug, e.g. 'thermometer', 'leaf', 'building-2', 'users'.", max_length=50)),
                ('project', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='catalog.projectpage')),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
