# Generated by Django 5.2.15 on 2026-06-22 07:03

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_projectpage_about_description_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='partners_cta_label',
            field=models.CharField(blank=True, help_text="CTA button label, e.g. 'Contact ACMAD'.", max_length=200),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='partners_cta_url',
            field=models.URLField(blank=True, help_text='External URL for the CTA button (mailto: or https://).'),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='partners_description',
            field=models.TextField(blank=True, help_text='Body paragraph for the Partners hero section.'),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='partners_image',
            field=models.ForeignKey(blank=True, help_text='Image shown on the right side of the Partners hero.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='partners_intro',
            field=models.CharField(blank=True, help_text="Green tagline, e.g. 'Built through climate, data and planning collaboration'.", max_length=500),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='partners_title',
            field=models.CharField(blank=True, help_text="Heading for the Partners page, e.g. 'Partners'.", max_length=300),
        ),
        migrations.CreateModel(
            name='ProjectPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('role', models.CharField(blank=True, help_text="Role label shown in green, e.g. 'Regional coordination'.", max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('website_url', models.URLField(blank=True, help_text='Partner website URL.')),
                ('logo', models.ForeignKey(blank=True, help_text='Partner logo image.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('project', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='catalog.projectpage')),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
