# Generated by Django 5.2.15 on 2026-06-22 07:23

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_projectpage_partners_cta_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Email address that receives contact form submissions from the Partners page.', max_length=254),
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_data', models.JSONField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_submissions', to='catalog.projectpage')),
            ],
            options={
                'verbose_name': 'Contact submission',
                'verbose_name_plural': 'Contact submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectContactField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(max_length=200)),
                ('field_type', models.CharField(choices=[('text', 'Short text'), ('email', 'Email address'), ('textarea', 'Long text')], default='text', max_length=20)),
                ('required', models.BooleanField(default=True)),
                ('placeholder', models.CharField(blank=True, max_length=200)),
                ('project', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_fields', to='catalog.projectpage')),
            ],
            options={
                'verbose_name': 'Contact form field',
                'verbose_name_plural': 'Contact form fields',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
