# Generated by Django 5.2.15 on 2026-06-22 07:35

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_projectpage_contact_email_contactsubmission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='feedback_description',
            field=models.TextField(blank=True, help_text='Short description shown below the subtitle.'),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='feedback_email',
            field=models.EmailField(blank=True, help_text='Email address that receives feedback form submissions.', max_length=254),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='feedback_intro',
            field=models.CharField(blank=True, help_text="Bold subtitle, e.g. 'Help improve e-SAFARI'.", max_length=500),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='feedback_title',
            field=models.CharField(blank=True, help_text="Feedback page title, e.g. 'Feedback'.", max_length=300),
        ),
        migrations.CreateModel(
            name='FeedbackSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_data', models.JSONField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_submissions', to='catalog.projectpage')),
            ],
            options={
                'verbose_name': 'Feedback submission',
                'verbose_name_plural': 'Feedback submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('question', models.CharField(max_length=400)),
                ('answer', models.TextField()),
                ('project', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='catalog.projectpage')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectFeedbackField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(max_length=200)),
                ('field_type', models.CharField(choices=[('text', 'Short text'), ('email', 'Email address'), ('textarea', 'Long text'), ('country_select', 'Country dropdown (from project countries)'), ('topic_select', 'Topic dropdown (define choices below)')], default='text', max_length=20)),
                ('required', models.BooleanField(default=True)),
                ('placeholder', models.CharField(blank=True, max_length=200)),
                ('choices', models.TextField(blank=True, help_text="For 'topic_select' only: one option per line.")),
                ('project', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_fields', to='catalog.projectpage')),
            ],
            options={
                'verbose_name': 'Feedback form field',
                'verbose_name_plural': 'Feedback form fields',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
