# Generated by Django 5.2.15 on 2026-06-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_projectpage_feedback_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='recaptcha_secret_key',
            field=models.CharField(blank=True, help_text='Google reCAPTCHA v2 secret key (private, never exposed in API). Used server-side to verify tokens.', max_length=200),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='recaptcha_site_key',
            field=models.CharField(blank=True, help_text='Google reCAPTCHA v2 site key (public). Leave blank to disable CAPTCHA on the feedback form.', max_length=200),
        ),
    ]
