# Generated by Django 5.2.15 on 2026-07-13 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_recaptcha_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfeature',
            name='linked_layer_id',
            field=models.SlugField(blank=True, help_text="dataset_id of the layer to preselect on the geoportal when this card is clicked (matches the 'id' field returned by /api/catalog/ui/layers), e.g. 'heat_stress'. Leave blank to open the geoportal with its default layer.", max_length=80),
        ),
    ]
