# Generated by Django 5.2.15 on 2026-08-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_projectfeature_linked_layer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticwmslayer',
            name='always_on_top',
            field=models.BooleanField(default=False, help_text='Keep this layer rendered above every other active layer, e.g. an admin-boundary overlay that should stay visible over hazard rasters.'),
        ),
    ]
