# Generated by Django 5.2.15 on 2026-08-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_staticwmslayer_always_on_top'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticwmslayer',
            name='display_on_homepage',
            field=models.BooleanField(default=False, help_text="Show this layer on the homepage hero map, alongside whichever hazard category the visitor has selected. Combine with 'Always on top' to keep it above the homepage's category raster too."),
        ),
    ]
