# Generated by Django 5.2.15 on 2026-08-10 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_staticwmslayer_display_on_homepage'),
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='example_notebook',
            field=models.ForeignKey(blank=True, help_text='Upload a .ipynb Jupyter notebook demonstrating access to this dataset.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document'),
        ),
        migrations.AddField(
            model_name='layer',
            name='example_notebook_description',
            field=models.CharField(blank=True, help_text='Optional one-line caption shown above the rendered notebook.', max_length=300),
        ),
    ]
