# Generated by Django 5.2.15 on 2026-08-10 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0030_layer_example_notebook_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='data_platforms_description',
            field=models.TextField(blank=True, help_text='Body paragraph describing the data infrastructure, shown on the Data Platforms page.'),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='data_platforms_image',
            field=models.ForeignKey(blank=True, help_text='Image shown on the right side of the Data Platforms hero section.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='data_platforms_title',
            field=models.CharField(blank=True, help_text="Heading for the Data Platforms overview section, e.g. 'The ACMAD Multi-Hazard Data Infrastructure'.", max_length=300),
        ),
    ]
