# Generated by Django 5.2.15 on 2026-08-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0031_projectpage_data_platforms_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoserverlayer',
            name='has_stac_collection',
            field=models.BooleanField(default=False, help_text="Whether this dataset has a real STAC collection registered in pgSTAC. Uncheck to hide the 'View STAC collection' link on the Data Platforms page."),
        ),
        migrations.AddField(
            model_name='layer',
            name='has_stac_collection',
            field=models.BooleanField(default=True, help_text="Whether this dataset has a real STAC collection registered in pgSTAC. Uncheck to hide the 'View STAC collection' link on the Data Platforms page."),
        ),
        migrations.AddField(
            model_name='staticwmslayer',
            name='has_stac_collection',
            field=models.BooleanField(default=False, help_text="Whether this dataset has a real STAC collection registered in pgSTAC. Uncheck to hide the 'View STAC collection' link on the Data Platforms page."),
        ),
    ]
