# Generated by Django 5.2.12 on 2026-09-03 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0032_geoserverlayer_has_stac_collection_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasetpage",
            name="allow_multiple_layers",
            field=models.BooleanField(
                default=False,
                help_text="Let this dataset carry more than one Layer style (e.g. one per data source), each with its own STAC collection id. Leave unchecked for the usual one-style-per-dataset case.",
            ),
        ),
        migrations.AddField(
            model_name="layer",
            name="stac_collection_id",
            field=models.CharField(
                blank=True,
                help_text="pgSTAC collection this style renders from and that ingestion targets. If blank, falls back to layer_id. Only meaningful on a dataset with 'allow multiple layer styles' checked; otherwise the dataset's own stac_collection_id is used.",
                max_length=120,
            ),
        ),
        migrations.AlterField(
            model_name="datasetpage",
            name="stac_collection_id",
            field=models.CharField(
                blank=True,
                help_text="If blank, defaults to dataset_id. Ignored when 'allow multiple layer styles' is checked - the collection is then taken from each Layer style.",
                max_length=120,
            ),
        ),
        migrations.AlterField(
            model_name="layer",
            name="dataset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="style_configs",
                to="catalog.datasetpage",
            ),
        ),
        migrations.AlterField(
            model_name="layer",
            name="example_notebook_description",
            field=models.CharField(
                blank=True,
                help_text="Optional one-line caption/description for the example notebook.",
                max_length=300,
            ),
        ),
        migrations.AlterField(
            model_name="layer",
            name="layer_id",
            field=models.SlugField(
                blank=True,
                help_text="Defaults to dataset_id for a single-style dataset. Required (and distinct) when the dataset allows multiple styles - e.g. precipitation-tercile-cpc-uni.",
                max_length=120,
                unique=True,
            ),
        ),
    ]
