# Generated by Django 5.2.12 on 2026-03-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('wis2_pull', 'WIS2 Pull'), ('noaa_import', 'NOAA Import'), ('ogimet_import', 'OGIMET Import'), ('manual_upload', 'Manual Upload'), ('other', 'Other')], db_index=True, default='other', max_length=30)),
                ('job_status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial Success')], db_index=True, default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('source_name', models.CharField(blank=True, help_text='Human-readable source label.', max_length=255, null=True)),
                ('records_received', models.PositiveIntegerField(default=0)),
                ('records_processed', models.PositiveIntegerField(default=0)),
                ('records_failed', models.PositiveIntegerField(default=0)),
                ('details', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ingestion_jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['job_type', 'created_at'], name='ing_job_type_time_idx'), models.Index(fields=['job_status'], name='ing_job_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='RawPayloadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('wis2', 'WIS2'), ('noaa', 'NOAA'), ('ogimet', 'OGIMET'), ('national_met', 'National Met'), ('other', 'Other')], db_index=True, default='other', max_length=30)),
                ('source_identifier', models.CharField(blank=True, help_text='Message ID, file name, URL, or broker topic reference.', max_length=255, null=True)),
                ('topic', models.CharField(blank=True, help_text='Useful for WIS2 MQTT topics.', max_length=500, null=True)),
                ('payload', models.JSONField(help_text='Original raw payload as received before normalization.')),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'raw_payload_logs',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['source_type', 'received_at'], name='raw_source_time_idx'), models.Index(fields=['processing_status'], name='raw_status_idx')],
            },
        ),
    ]
