# Generated by Django 5.2.12 on 2026-03-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ingestionjob',
            name='ing_job_type_time_idx',
        ),
        migrations.RemoveIndex(
            model_name='ingestionjob',
            name='ing_job_status_idx',
        ),
        migrations.AddField(
            model_name='rawpayloadlog',
            name='canonical_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawpayloadlog',
            name='content_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rawpayloadlog',
            name='data_datetime',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='rawpayloadlog',
            name='data_id',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='rawpayloadlog',
            name='decision',
            field=models.CharField(blank=True, help_text='Example: candidate, skipped_non_africa, unsupported_type.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rawpayloadlog',
            name='global_cache',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rawpayloadlog',
            name='metadata_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='rawpayloadlog',
            name='pubtime',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingestionjob',
            name='job_type',
            field=models.CharField(choices=[('wis2_consumer', 'WIS2 Consumer'), ('noaa_import', 'NOAA Import'), ('ogimet_import', 'OGIMET Import'), ('manual_upload', 'Manual Upload'), ('other', 'Other')], db_index=True, default='wis2_consumer', max_length=30),
        ),
        migrations.AlterField(
            model_name='ingestionjob',
            name='source_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawpayloadlog',
            name='payload',
            field=models.JSONField(blank=True, help_text='Optional raw notification JSON. Keep only when useful.', null=True),
        ),
        migrations.AlterField(
            model_name='rawpayloadlog',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('downloaded', 'Downloaded'), ('processed', 'Processed'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='rawpayloadlog',
            name='source_identifier',
            field=models.CharField(blank=True, db_index=True, help_text='Notification id or message identifier.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawpayloadlog',
            name='source_type',
            field=models.CharField(choices=[('wis2', 'WIS2'), ('noaa', 'NOAA'), ('ogimet', 'OGIMET'), ('national_met', 'National Met'), ('other', 'Other')], db_index=True, default='wis2', max_length=30),
        ),
        migrations.AlterField(
            model_name='rawpayloadlog',
            name='topic',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True),
        ),
        migrations.AddIndex(
            model_name='rawpayloadlog',
            index=models.Index(fields=['data_id'], name='raw_data_id_idx'),
        ),
    ]
