# Generated by Django 5.2.12 on 2026-03-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0002_remove_ingestionjob_ing_job_type_time_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='rawpayloadlog',
            name='raw_source_time_idx',
        ),
        migrations.RemoveIndex(
            model_name='rawpayloadlog',
            name='raw_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='rawpayloadlog',
            name='raw_data_id_idx',
        ),
        migrations.AddField(
            model_name='rawpayloadlog',
            name='downloaded_content_type',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='rawpayloadlog',
            name='payload_preview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawpayloadlog',
            name='payload_size_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rawpayloadlog',
            name='decision',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rawpayloadlog',
            name='payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rawpayloadlog',
            name='source_identifier',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
