# Generated by Django 5.2.12 on 2026-03-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0003_remove_rawpayloadlog_raw_source_time_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawpayloadlog',
            name='local_file_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
