# Generated by Django 5.2.10 on 2026-02-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VectorIngestRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_id', models.CharField(max_length=128)),
                ('href', models.CharField(max_length=512)),
                ('table', models.CharField(max_length=128)),
                ('mode', models.CharField(default='replace', max_length=16)),
                ('status', models.CharField(choices=[('queued', 'queued'), ('processing', 'processing'), ('completed', 'completed'), ('failed', 'failed')], default='queued', max_length=16)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
