# Generated by Django 5.2.10 on 2026-02-03 13:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vector_ingest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VectorIngestJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dataset_name', models.CharField(max_length=255)),
                ('table_name', models.CharField(max_length=63)),
                ('schema_name', models.CharField(default='public', max_length=63)),
                ('srid', models.IntegerField(default=4326)),
                ('upload', models.FileField(upload_to='vector_uploads/%Y/%m/%d/')),
                ('ingest_status', models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('ready', 'ready'), ('failed', 'failed')], default='pending', max_length=16)),
                ('ingest_error', models.TextField(blank=True, default='')),
                ('archive_status', models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('ready', 'ready'), ('failed', 'failed')], default='pending', max_length=16)),
                ('archive_error', models.TextField(blank=True, default='')),
                ('archive_uri', models.TextField(blank=True, default='')),
                ('row_count', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='VectorIngestRun',
        ),
    ]
