# Generated by Django 5.2.15 on 2026-08-05 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0027_projectfeature_linked_layer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Admin label, e.g. 'ACMAD WWFD ensemble5'.", max_length=150, unique=True)),
                ('source_base_url', models.URLField(help_text='THREDDS fileServer base (not the catalog/ HTML browsing base), e.g. https://sgbd.acmad.org/thredds/fileServer/ACMAD/WWFD/forecastinservice/ensemble5', max_length=500)),
                ('folder_pattern', models.CharField(default='{run_date:%Y%m%d}', help_text='Dated subfolder, rendered with run_date, e.g. {run_date:%Y%m%d}', max_length=200)),
                ('enabled', models.BooleanField(default=True)),
                ('schedule_hour_utc', models.PositiveSmallIntegerField(default=7, help_text="Earliest UTC hour to attempt today's run.")),
                ('schedule_minute_utc', models.PositiveSmallIntegerField(default=0)),
                ('retry_interval_minutes', models.PositiveIntegerField(default=30, help_text='Minutes between retries while any mapped file is not yet available.')),
                ('retry_until_hour_utc', models.PositiveSmallIntegerField(default=20, help_text='Stop retrying for the day after this UTC hour; the run is left partial.')),
                ('request_timeout_seconds', models.PositiveIntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DownloadRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_date', models.DateField(help_text='Forecast issue date rendered into folder_pattern/filename_pattern.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('partial', 'Partial'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempted_at', models.DateTimeField(blank=True, help_text='Used to throttle retries via workflow.retry_interval_minutes.', null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('total_files', models.PositiveIntegerField(default=0)),
                ('completed_files', models.PositiveIntegerField(default=0)),
                ('failed_files', models.PositiveIntegerField(default=0)),
                ('not_yet_available_files', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='thredds_ingestion.downloadworkflow')),
            ],
            options={
                'ordering': ['-run_date'],
            },
        ),
        migrations.CreateModel(
            name='DownloadWorkflowFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', help_text="Optional admin-facing label, e.g. '5-day mean' or 'POP 50mm'.", max_length=150)),
                ('filename_pattern', models.CharField(help_text="Rendered against run_date[, lead_hours, threshold]. Examples: '5daymean_{run_date:%Y%m%d}.tif', 'mix{run_date:%Y%m%d}_{lead_hours}.tif', 'pop{run_date:%Y%m%d}_{threshold}_{lead_hours}.tif'.", max_length=300)),
                ('lead_hours_csv', models.CharField(blank=True, default='', help_text="Comma-separated lead hours, e.g. '24,96,144'. Leave blank for single-file-per-day products with no {lead_hours} placeholder.", max_length=200)),
                ('threshold_label', models.CharField(blank=True, default='', help_text="Literal substituted for {threshold} in filename_pattern, e.g. '50mm'.", max_length=30)),
                ('item_id_pattern', models.CharField(blank=True, default='', help_text="Optional STAC item_id override, rendered with the same context as filename_pattern. Defaults to '{dataset_id}_{run_date:%Y%m%d}' (no lead hours) or '{dataset_id}_{run_date:%Y%m%d}_{lead_hours}h' (with lead hours). Must vary by lead_hours if this mapping has more than one - the default already does.", max_length=200)),
                ('overwrite_existing', models.BooleanField(default=False, help_text='If true, re-download/re-ingest even when a DownloadRunItem already succeeded.')),
                ('enabled', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset', models.ForeignKey(help_text='Target dataset (existing DatasetPage, matched by dataset_id).', on_delete=django.db.models.deletion.PROTECT, related_name='thredds_download_files', to='catalog.datasetpage')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='thredds_ingestion.downloadworkflow')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DownloadRunItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_hours', models.PositiveIntegerField(default=0, help_text='0 means this workflow_file has no lead-hour dimension.')),
                ('filename', models.CharField(max_length=300)),
                ('source_url', models.URLField(max_length=600)),
                ('item_id', models.CharField(help_text='Deterministic STAC item id. Globally unique - a collision here almost always means item_id_pattern is missing {run_date} or {lead_hours}.', max_length=250, unique=True)),
                ('valid_datetime', models.DateTimeField(help_text='run_date + lead_hours (or run_date midnight UTC when lead_hours=0).')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('not_yet_available', 'Not Yet Available'), ('downloading', 'Downloading'), ('ingesting', 'Ingesting'), ('completed', 'Completed'), ('skipped', 'Skipped'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('ingestion_run_id', models.PositiveIntegerField(blank=True, help_text='ingest.models.IngestionRun.id this item was pushed through.', null=True)),
                ('minio_href', models.CharField(blank=True, default='', max_length=500)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='thredds_ingestion.downloadrun')),
                ('workflow_file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='run_items', to='thredds_ingestion.downloadworkflowfile')),
            ],
            options={
                'ordering': ['workflow_file__sort_order', 'lead_hours'],
            },
        ),
        migrations.AddIndex(
            model_name='downloadrun',
            index=models.Index(fields=['workflow', 'status'], name='thredds_ing_workflo_7f499a_idx'),
        ),
        migrations.AddConstraint(
            model_name='downloadrun',
            constraint=models.UniqueConstraint(fields=('workflow', 'run_date'), name='uniq_download_run_per_day'),
        ),
        migrations.AddIndex(
            model_name='downloadrunitem',
            index=models.Index(fields=['status'], name='thredds_ing_status_5c9d6a_idx'),
        ),
        migrations.AddConstraint(
            model_name='downloadrunitem',
            constraint=models.UniqueConstraint(fields=('run', 'workflow_file', 'lead_hours'), name='uniq_download_run_item_per_file_leadhour'),
        ),
    ]
