# Generated by Django 5.2.15 on 2026-08-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thredds_ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadworkflow',
            name='catch_up_days',
            field=models.PositiveSmallIntegerField(default=3, help_text="On every scheduled tick, also re-check this many previous days (not just today) and retry any that aren't completed yet - self-heals after an outage or a day with not-yet-available files, without operator intervention. For a large historical backfill, use the run_download_workflow management command instead of raising this."),
        ),
    ]
