# Generated by Django 5.2.15 on 2026-08-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thredds_ingestion', '0002_downloadworkflow_catch_up_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadworkflowfile',
            name='filename_pattern',
            field=models.CharField(help_text="Rendered against run_date[, lead_hours, valid_date, threshold]. valid_date is run_date + lead_hours, always available even without lead_hours_csv set. Examples: '5daymean_{run_date:%Y%m%d}.tif', 'mix{run_date:%Y%m%d}_{lead_hours}.tif', 'pop{run_date:%Y%m%d}_{threshold}_{lead_hours}.tif', 'heat_index_{run_date:%Y%m%d}_{valid_date:%Y%m%d}.tif' (lead_hours_csv in multiples of 24 for a day-granularity product like this one).", max_length=300),
        ),
        migrations.AlterField(
            model_name='downloadworkflowfile',
            name='lead_hours_csv',
            field=models.CharField(blank=True, default='', help_text="Comma-separated lead hours, e.g. '24,96,144'. '0' is a valid lead (e.g. a same-day forecast in a '0,24,48' series) - leave the whole field blank instead for single-file-per-day products with no lead dimension at all.", max_length=200),
        ),
    ]
