# Generated by Django 5.2.15 on 2026-08-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thredds_ingestion', '0003_alter_downloadworkflowfile_filename_pattern_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadworkflowfile',
            name='datetime_from_run_date',
            field=models.BooleanField(default=False, help_text="If true, this item's STAC datetime (and valid_datetime) is run_date alone, ignoring lead_hours - use when the forecast issue date should be what's queryable/displayed (e.g. 'today's heat index outlook'), not the date the forecast is valid for. filename_pattern/item_id_pattern are unaffected - {valid_date}/{lead_hours} there still reflect the real lead."),
        ),
    ]
