# Generated by Django 5.2.15 on 2026-08-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thredds_ingestion', '0004_downloadworkflowfile_datetime_from_run_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadrunitem',
            name='valid_end_datetime',
            field=models.DateTimeField(blank=True, help_text='Window end (valid_datetime + workflow_file.validity_hours); blank for point-in-time items.', null=True),
        ),
        migrations.AddField(
            model_name='downloadworkflowfile',
            name='validity_hours',
            field=models.PositiveIntegerField(blank=True, help_text="If set, this item covers a window rather than an instant - it's ingested with start_datetime/end_datetime instead of a single datetime, e.g. 120 for a 5-day mean. The window starts at the same anchor datetime_from_run_date controls (run_date, or run_date + lead_hours) and ends validity_hours later. Leave blank for point-in-time products (the common case).", null=True),
        ),
        migrations.AlterField(
            model_name='downloadrunitem',
            name='valid_datetime',
            field=models.DateTimeField(help_text='Window start (or the single instant, when workflow_file.validity_hours is unset): run_date + lead_hours, or run_date alone if datetime_from_run_date.'),
        ),
        migrations.AlterField(
            model_name='downloadworkflowfile',
            name='datetime_from_run_date',
            field=models.BooleanField(default=False, help_text="If true, this item's STAC datetime (and valid_datetime) is run_date alone, ignoring lead_hours - use when the forecast issue date should be what's queryable/displayed (e.g. 'today's heat index outlook'), not the date the forecast is valid for. filename_pattern/item_id_pattern are unaffected - {valid_date}/{lead_hours} there still reflect the real lead. Also controls the start of the window below when validity_hours is set."),
        ),
    ]
