# Generated by Django 5.2.17 on 2026-08-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thredds_ingestion', '0005_downloadrunitem_valid_end_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadworkflowfile',
            name='csv_value_column',
            field=models.CharField(blank=True, default='', help_text="Required when the downloaded file is a CSV: name of the column holding raster values (e.g. 'Vigilance'). Converted to a GeoTIFF via utils.raster_converstions.csv_to_raster before upload/ingest - x/y columns and resolution use that function's defaults ('Data$x', 'y', 0.5°).", max_length=100),
        ),
    ]
