# Generated by Django 5.2.17 on 2026-08-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thredds_ingestion', '0006_downloadworkflowfile_csv_value_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadworkflowfile',
            name='csv_x_res',
            field=models.FloatField(blank=True, help_text='Longitude grid resolution in degrees for CSV->raster conversion. Leave blank to use the 0.5° default.', null=True),
        ),
        migrations.AddField(
            model_name='downloadworkflowfile',
            name='csv_y_res',
            field=models.FloatField(blank=True, help_text='Latitude grid resolution in degrees for CSV->raster conversion. Leave blank to use the 0.5° default.', null=True),
        ),
        migrations.AlterField(
            model_name='downloadworkflowfile',
            name='csv_value_column',
            field=models.CharField(blank=True, default='', help_text="Required when the downloaded file is a CSV: name of the column holding raster values (e.g. 'Vigilance'). Converted to a GeoTIFF via utils.raster_converstions.csv_to_raster before upload/ingest - x/y columns default to 'Data$x'/'y'; resolution defaults to csv_x_res/csv_y_res below, or 0.5° each if those are also blank.", max_length=100),
        ),
    ]
