# Generated by Django 5.2.12 on 2026-09-02 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thredds_ingestion", "0007_downloadworkflowfile_csv_x_res_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="downloadworkflow",
            name="anchor_month",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Seasonal cadence only: first calendar month of the season (JJA -> 6, OND -> 10, DJF -> 12). The run_date is the 1st of this month.",
            ),
        ),
        migrations.AddField(
            model_name="downloadworkflow",
            name="cadence",
            field=models.CharField(
                choices=[
                    ("daily", "Daily"),
                    ("monthly", "Monthly"),
                    ("seasonal", "Seasonal"),
                ],
                default="daily",
                help_text="Drives how the Beat scheduler picks run_dates. daily: today + previous catch_up_days days. monthly: last month + previous catch_up_days *months* (1st-of-month run_date). seasonal: one run per year anchored at anchor_month, + previous catch_up_days *years*. Backfill via the run_download_workflow command is unaffected by this.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="downloadworkflow",
            name="publish_month_offset",
            field=models.PositiveSmallIntegerField(
                default=3,
                help_text="Seasonal cadence only: months after anchor_month when the observed data is expected (3-month season -> ~3; a 5-month season -> ~5; a full-year 'season' -> ~13).",
            ),
        ),
        migrations.AddField(
            model_name="downloadworkflow",
            name="retry_window_days",
            field=models.PositiveSmallIntegerField(
                default=45,
                help_text="Monthly/seasonal cadence: keep retrying the newest period for this many days after its publish day, then stop (older periods still self-heal until they scroll out of catch_up).",
            ),
        ),
        migrations.AddField(
            model_name="downloadworkflow",
            name="schedule_day_of_month",
            field=models.PositiveSmallIntegerField(
                default=8,
                help_text="Monthly/seasonal cadence: earliest day of the publish month to start attempting a period (observed products land weeks after the period ends). Monthly -> day of the month after the data month; seasonal -> day of the month anchor_month + publish_month_offset.",
            ),
        ),
        migrations.AlterField(
            model_name="downloadworkflow",
            name="catch_up_days",
            field=models.PositiveSmallIntegerField(
                default=3,
                help_text="On every scheduled tick, also re-check this many previous periods (days for daily cadence, months for monthly, years for seasonal) and retry any that aren't completed yet - self-heals after an outage or a period with not-yet-available files, without operator intervention. For a large historical backfill, use the run_download_workflow management command instead of raising this.",
            ),
        ),
        migrations.AlterField(
            model_name="downloadworkflow",
            name="folder_pattern",
            field=models.CharField(
                default="{run_date:%Y%m%d}",
                help_text="Dated subfolder, rendered with run_date (plus {month_abbr}/{month_name}, always English). Daily: {run_date:%Y%m%d}. Monthly: {month_abbr}/tif. Seasonal: a literal season folder like 'JJA/tif' (the season isn't derivable from a date - one workflow per season).",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="downloadworkflow",
            name="retry_until_hour_utc",
            field=models.PositiveSmallIntegerField(
                default=20,
                help_text="Daily cadence only: stop retrying for the day after this UTC hour; the run is left partial.",
            ),
        ),
        migrations.AlterField(
            model_name="downloadworkflow",
            name="schedule_hour_utc",
            field=models.PositiveSmallIntegerField(
                default=7,
                help_text="Daily cadence only: earliest UTC hour to attempt today's run.",
            ),
        ),
    ]
