# Generated by Django 5.2.12 on 2026-09-03 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0033_datasetpage_allow_multiple_layers_and_more"),
        ("thredds_ingestion", "0008_downloadworkflow_anchor_month_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="downloadworkflowfile",
            name="layer",
            field=models.ForeignKey(
                blank=True,
                help_text="Target Layer style, for a dataset with multiple sources/styles. When set, ingestion goes into this layer's STAC collection (stac_collection_id, or layer_id if blank) instead of the dataset's. Must belong to 'dataset' above. Leave blank for the usual single-collection dataset.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="thredds_download_files",
                to="catalog.layer",
            ),
        ),
    ]
