# Generated by Django 5.2.12 on 2026-03-14 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_code', models.CharField(max_length=100, unique=True)),
                ('source_name', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('wis2', 'WIS2'), ('noaa', 'NOAA'), ('ogimet', 'Ogimet'), ('national_met', 'National Meteorological Service'), ('aws_direct', 'Direct AWS Feed'), ('other', 'Other')], db_index=True, default='other', max_length=50)),
                ('endpoint_url', models.URLField(blank=True, null=True)),
                ('protocol', models.CharField(choices=[('mqtt', 'MQTT'), ('http', 'HTTP'), ('https', 'HTTPS'), ('ftp', 'FTP'), ('sftp', 'SFTP'), ('file', 'File'), ('api', 'API'), ('other', 'Other')], default='other', max_length=20)),
                ('contact_info', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'data_sources',
                'ordering': ['source_name'],
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('owner_org', models.CharField(blank=True, max_length=255, null=True)),
                ('public_api_allowed', models.BooleanField(default=False)),
                ('dashboard_allowed', models.BooleanField(default=False)),
                ('internal_allowed', models.BooleanField(default=True)),
                ('partner_allowed', models.BooleanField(default=False)),
                ('raw_download_allowed', models.BooleanField(default=False)),
                ('aggregate_allowed', models.BooleanField(default=True)),
                ('station_visible', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'policies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_code', models.CharField(max_length=120, unique=True)),
                ('dataset_name', models.CharField(max_length=255)),
                ('variable_family', models.CharField(blank=True, help_text='Example: synop, rainfall, temperature, station_health.', max_length=100, null=True)),
                ('temporal_resolution', models.CharField(blank=True, help_text='Example: 10min, hourly, daily.', max_length=50, null=True)),
                ('licence_text', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='sources.datasource')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='datasets', to='sources.policy')),
            ],
            options={
                'db_table': 'datasets',
                'ordering': ['dataset_name'],
                'indexes': [models.Index(fields=['dataset_code'], name='datasets_code_idx'), models.Index(fields=['is_active'], name='datasets_active_idx')],
            },
        ),
    ]
